### ISSUE TITLE
Plain Text Passwords

### ISSUE THREAD

**Issue by navidkhn1** [bigdroptech/square1-core#94]
In list view for accounts, it should be possible to request plain text passwords for the objects, by passing an additional GET parameter.

**Comment by elflamo** [comment]
First, there is a difference between hashing and encryption. SHA256 is a hashing function, not an encryption function.

Secondly, since SHA256 is not an encryption function, it cannot be decrypted. What you mean is probably reversing it. In that case, SHA256 cannot be reversed because it's a one-way function. Reversing it would cause a preimage attack, which defeats its design goal.

Thirdly, SHA256 verification works by computing it again and comparing the result with the result at hand. If both results match, then the verification is successful.
